CREATE TABLE IF NOT EXISTS video_external_api_configs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL DEFAULT '',
  group_name VARCHAR(100) NOT NULL DEFAULT '默认',
  request_url VARCHAR(500) NOT NULL DEFAULT '',
  request_format VARCHAR(20) NOT NULL DEFAULT 'json',
  headers_json TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  response_json TEXT NOT NULL,
  result_video_url_field VARCHAR(255) NOT NULL DEFAULT '',
  result_video_base64_field VARCHAR(255) NOT NULL DEFAULT '',
  result_cover_url_field VARCHAR(255) NOT NULL DEFAULT '',
  call_mode VARCHAR(20) NOT NULL DEFAULT 'async',
  submit_success_statuses_json TEXT NOT NULL,
  poll_url VARCHAR(500) NOT NULL DEFAULT '',
  poll_method VARCHAR(10) NOT NULL DEFAULT 'GET',
  poll_headers_json TEXT NOT NULL,
  poll_payload_json TEXT NOT NULL,
  task_id_field VARCHAR(255) NOT NULL DEFAULT '',
  result_status_field VARCHAR(255) NOT NULL DEFAULT '',
  result_success_values_json TEXT NOT NULL,
  result_failed_values_json TEXT NOT NULL,
  result_error_field VARCHAR(255) NOT NULL DEFAULT '',
  poll_result_video_url_field VARCHAR(255) NOT NULL DEFAULT '',
  poll_result_video_base64_field VARCHAR(255) NOT NULL DEFAULT '',
  poll_result_cover_url_field VARCHAR(255) NOT NULL DEFAULT '',
  poll_interval_seconds INT NOT NULL DEFAULT 5,
  poll_timeout_seconds INT NOT NULL DEFAULT 600,
  status VARCHAR(20) NOT NULL DEFAULT 'enabled',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS video_external_api_scene_bindings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  scene_key VARCHAR(50) NOT NULL UNIQUE,
  is_deleted BOOLEAN NOT NULL DEFAULT 0,
  scene_label VARCHAR(100) NOT NULL DEFAULT '',
  scene_description VARCHAR(255) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  hide_aspect_ratio BOOLEAN NOT NULL DEFAULT 0,
  hide_duration BOOLEAN NOT NULL DEFAULT 0,
  hide_resolution BOOLEAN NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'enabled',
  api_config_id INT NULL,
  backup_api_config_id INT NULL,
  display_name VARCHAR(100) NOT NULL DEFAULT '',
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  availability_mode VARCHAR(20) NOT NULL DEFAULT 'both',
  max_reference_images INT NOT NULL DEFAULT 1,
  credit_billing_mode VARCHAR(20) NOT NULL DEFAULT 'fixed',
  credit_cost INT NOT NULL DEFAULT 0,
  per_second_credit_cost INT NOT NULL DEFAULT 0,
  duration_options_json TEXT NOT NULL,
  aspect_ratio_options_json TEXT NOT NULL,
  resolution_options_json TEXT NOT NULL,
  resolution_mapping_json TEXT NOT NULL,
  resolution_credit_costs_json TEXT NOT NULL,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_video_scene_api_config FOREIGN KEY (api_config_id) REFERENCES video_external_api_configs(id),
  CONSTRAINT fk_video_scene_backup_api_config FOREIGN KEY (backup_api_config_id) REFERENCES video_external_api_configs(id)
);

CREATE TABLE IF NOT EXISTS video_tasks (
  id INT PRIMARY KEY AUTO_INCREMENT,
  business_id VARCHAR(32) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  model VARCHAR(50) NOT NULL DEFAULT '',
  source VARCHAR(20) NOT NULL DEFAULT 'web',
  prompt TEXT NOT NULL,
  duration_seconds INT NOT NULL DEFAULT 5,
  aspect_ratio VARCHAR(20) NOT NULL DEFAULT '',
  resolution VARCHAR(50) NOT NULL DEFAULT '',
  reference_images TEXT NOT NULL,
  credit_cost INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  error_message TEXT NOT NULL,
  provider_api_config_id INT NULL,
  provider_task_id VARCHAR(255) NOT NULL DEFAULT '',
  provider_status VARCHAR(50) NOT NULL DEFAULT '',
  provider_error_message TEXT NOT NULL,
  provider_response_preview TEXT NOT NULL,
  poll_count INT NOT NULL DEFAULT 0,
  last_polled_at DATETIME NULL,
  next_poll_at DATETIME NULL,
  used_fallback_api BOOLEAN NOT NULL DEFAULT 0,
  is_deleted BOOLEAN NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enqueued_at DATETIME NULL,
  request_started_at DATETIME NULL,
  request_finished_at DATETIME NULL,
  updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_video_tasks_user_status_created (user_id, status, created_at),
  KEY idx_video_tasks_next_poll (next_poll_at),
  CONSTRAINT fk_video_tasks_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS video_results (
  id INT PRIMARY KEY AUTO_INCREMENT,
  task_id INT NOT NULL,
  video_url VARCHAR(500) NOT NULL DEFAULT '',
  cover_url VARCHAR(500) NOT NULL DEFAULT '',
  video_format VARCHAR(50) NOT NULL DEFAULT '',
  video_size_bytes BIGINT NOT NULL DEFAULT 0,
  duration_seconds INT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  error_message VARCHAR(2000) NOT NULL DEFAULT '',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_video_results_task (task_id),
  CONSTRAINT fk_video_results_task FOREIGN KEY (task_id) REFERENCES video_tasks(id)
);

CREATE TABLE IF NOT EXISTS video_task_api_attempts (
  id INT PRIMARY KEY AUTO_INCREMENT,
  task_id INT NOT NULL,
  result_id INT NULL,
  api_config_id INT NULL,
  api_config_name VARCHAR(100) NOT NULL DEFAULT '',
  attempt_index INT NOT NULL DEFAULT 1,
  is_fallback BOOLEAN NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'failed',
  http_status INT NULL,
  error_message TEXT NULL,
  duration_ms INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_video_task_attempts_task (task_id),
  KEY idx_video_task_attempts_result (result_id),
  CONSTRAINT fk_video_task_attempts_task FOREIGN KEY (task_id) REFERENCES video_tasks(id),
  CONSTRAINT fk_video_task_attempts_result FOREIGN KEY (result_id) REFERENCES video_results(id),
  CONSTRAINT fk_video_task_attempts_api_config FOREIGN KEY (api_config_id) REFERENCES video_external_api_configs(id)
);
